### ISSUE TITLE
FileNotFoundError when importing torch_scope

### ISSUE THREAD

**Issue by ouwyukha** [LiyuanLucasLiu/Torch-Scope#6]
Hello, i'm having trouble while importing torch_scope. I'm using python 3.7 and pytorch 1.8.1.
Is there any requirement that i don't have or torch_scope simply doesn't work on my configuration? Thankss

![image](https://user-images.githubusercontent.com/46920472/117643181-4f708000-b1b2-11eb-8033-a8da0d48daea.png)

**Comment by LiyuanLucasLiu** [comment]
Thanks for your interest in our project!

However, our project doesn't support windows cmd now (since it has some settings related to bash)... 

You can use docker to run a linux subsystem on windows, i feel that is better/easier way to run pytorch on windows.
